Search local shards directly to find shard to evict
mosaicml/streaming pull request #791
Opened 2024-09-27 22:36 UTC by coryMosaicML

This PR changes the search for coldest shard to avoid looping over remote shards by considering local shards only as possible candidates for eviction.

2024-09-27 22:38 UTC, j316chuck commented
https://github.com/databricks-mosaic/regression-testing/actions/runs/11078601583 

Adding regression runs here^

2024-09-27 22:41 UTC, j316chuck commented
You can invoke like this
<img width="1386" alt="Screenshot 2024-09-27 at 3 40 49 PM" src="https://github.com/user-attachments/assets/6838f5db-faac-4322-96b4-fee1ac28108c">

2024-09-27 22:41 UTC, j316chuck commented
You can invoke like this
<img width="1386" alt="Screenshot 2024-09-27 at 3 40 49 PM" src="https://github.com/user-attachments/assets/d200ab4b-e98e-415c-9172-7e3be4175282">

2024-09-27 22:42 UTC, j316chuck commented
You can invoke like this 
<img width="1726" alt="Screenshot 2024-09-27 at 3 41 37 PM" src="https://github.com/user-attachments/assets/fa30e8d1-2aac-4240-9b4a-2e51a69e1c00">

2024-09-30 21:46 UTC, j316chuck commented
<img width="663" alt="Screenshot 2024-09-30 at 2 45 49 PM" src="https://github.com/user-attachments/assets/2f016f76-fda9-4ce8-a367-4a4651849cdc">

Throughput looks [normal](https://databricks.slack.com/archives/C05T1A4UMT8/p1727483855679929 
), can we merge?

2024-09-30 21:54 UTC, XiaohanZhangCMU requested changes
What if the evicted shard is currently used by other processes? Is there a mechanism to prevent that?

2024-09-30 21:54 UTC, XiaohanZhangCMU commented on streaming/base/dataset.py
> +        indices = np.where(states == 3)[0]
suggest: == _ShardState.LOCAL

2024-09-30 22:01 UTC, snarayan21 reviewed
looks nice! agreed with @XiaohanZhangCMU 's comments. I don't think we actually need a mechanism to make sure the local shard isn't used...according to regression tests, this seems fine to me. probabilistically is probably okay.

2024-09-30 23:15 UTC, XiaohanZhangCMU commented
@snarayan21 yeah, I'm ok with it. The question I had is not valid, which should have been handled by the get_item retry logic already.

2024-10-01 17:07 UTC, closed without merging

2024-10-01 17:07 UTC, coryMosaicML commented
Closing because it is superseded by [795](https://github.com/mosaicml/streaming/pull/795).